//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volleyball.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppException
    {
        public long ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string Method { get; set; }
        public string Page { get; set; }
        public string Line { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ExceptionType { get; set; }
        public Nullable<bool> IsSolved { get; set; }
        public string SolutionRemark { get; set; }
        public string Object { get; set; }
    }
}
