//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volleyball.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentTeam
    {
        public int ID { get; set; }
        public Nullable<int> TournamentID { get; set; }
        public Nullable<int> Team1 { get; set; }
        public Nullable<int> Team2 { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team3 { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
